server:
  port: 8082

spring:
  application:
    name: chatbot-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/chatbot?currentSchema=chatbot
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: chatbot
        jdbc:
          time_zone: UTC
  # sql:
  #   init:
  #     mode: always
  #     data-locations: classpath:data.sql
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:4b
        options:
          temperature: 0.7
          top-p: 0.95
          top-k: 50

logging:
  level:
    org.springframework: INFO
    org.springframework.ai.chat.client.advisor: DEBUG
    com.example.chatbot: DEBUG

cors:
  allowed-origins: http://localhost:5173